### ISSUE TITLE
[Login Form] The 'Пошта' inscription instead of the 'Email' inscription is displayed in the placeholder field on the login form 

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#101]
**Environment:**
Windows 10 Pro 19045.4046
Google Chrome 121.0.6167.187, x64
Windows 10 22H2 19045.4046, 64-bit
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible**: always

**Build found**: 07.03.2024_12:30

**Preconditions:**
1. The home page is opened

**Steps to reproduce:**

1. The [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) site is opened
2. Click on the ‘Кабінет’ icon in the footer of the site
3. Pay attention to the first placeholder field 

**Actual result:**
The 'Пошта' inscription instead of the 'Email' inscription is displayed in the placeholder field on the login form 

**Expected result:**
The 'Email' inscription is displayed in the placeholder field on the login form

![2024-03-07](https://github.com/kamilka13me/marketplace_teamchallenge/assets/142516059/48eb1c33-32ef-4627-ac3b-81daabf19c66)

**Comment by olehivanovw** [comment]
Fix. @ElinaApanasenko
Actual result:
The 'Email' inscription is displayed in the placeholder field on the login form
![Screenshot_1](https://github.com/kamilka13me/marketplace_teamchallenge/assets/121825752/41969617-51e6-4233-958e-4aa63185cb86)
