### ISSUE TITLE
[modal window] The 'Зареєструватись' inscription instead of the 'Зареєструватися' inscription is displayed after clicking the 'Кабінет' icon

### ISSUE THREAD

**Issue by Viktoriia0106** [kamilka13me/marketplace_teamchallenge#111]
**Environment:**
Windows 10 Pro 19045.4046
Google Chrome 121.0.6167.187, x64
Windows 10 22H2 19045.4046, 64-bit
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible:** always

**Build found**: 11.03.2024_20:30

**Steps to reproduce:**
The [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) site is opened
Click the ‘Кабінет’ icon in the header of the site
Pay attention to the 'Зареєструватись' link and compare it with a mockup

**Actual result:**
 The 'Зареєструватись' inscription instead of the 'Зареєструватися' inscription is displayed in the modal window after clicking the 'Кабінет' icon

**Expected result:**
The 'Зареєструватися' inscription is displayed in the modal window after clicking the 'Кабінет' icon according to the mock-up

![image_2024-03-11_204613494](https://github.com/kamilka13me/marketplace_teamchallenge/assets/109147739/266e2a4e-377d-4344-bdb0-65790e568176)
![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/109147739/f4f287f0-3d39-4dfd-84a5-e7c8d3197154)

[Mock-up link](https://www.figma.com/file/5NnpV2rE62D0aCtwGB30F8/Simple-project-Marketplace?type=design&node-id=775-2539&mode=design&t=VqGUP3ZKft7jpNOA-4)

**Comment by olehivanovw** [comment]
Fix @Viktoriia0106 
Actual result:
The 'Зареєструватися' inscription is displayed in the modal window after clicking the 'Кабінет' icon according to the mock-up

![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/121825752/b1bf2093-5ff6-4258-bda6-67315f1359ca)
