### ISSUE TITLE
['Кабінет' Tab, Main page] The password without capital letter is accepted instead of error message after entering invalid data into mandatory field

### ISSUE THREAD

**Issue by Viktoriia0106** [kamilka13me/marketplace_teamchallenge#130]
**Environment:**

Windows 10 22H2 19045.4046, 64-bit
Google Chrome 121.0.6167.187, x64
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible:** always

**Build found:** 18.03.2024_14:30

**Steps to reproduce:**

1. The [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) site is opened
2. Click the ‘Кабінет’ icon in the header of the site
3. Enter a valid E-mail (e.g. [peach@ukr.net](mailto:peach@ukr.net))
4. Enter a password without the capital letter (e.g. 111111111)
5. Pay attention to the result

**Actual result:**
The password without capital letter is accepted instead of error message after entering invalid data into mandatory field

**Expected result:**
The password without capital letter is not accepted and error message with password requirements is shown after entering invalid data into mandatory field, 'Увійти' button is not active

[User story MT-15](https://marketplacetc.atlassian.net/browse/MT-15)

![No letters as valid data](https://github.com/kamilka13me/marketplace_teamchallenge/assets/109147739/235395ea-5e0d-4997-b731-152e6e3bf53b)

**Comment by olehivanovw** [comment]
Fix @Viktoriia0106, Added this check to the password field in the login form.

Actual result:
The password without capital letter is not accepted and error message with password requirements is shown after entering invalid data into mandatory field, 'Увійти' button is not active.

![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/121825752/501dae1f-71b6-4c23-9e41-8d7a6b5346b1)


Please make this issue is closed if the bug is fixed.

**Comment by Viktoriia0106** [comment]
@olehivanovw, from the current error message it is not understandable what is entered wrong. The condition "at least 9 symbols and the capital letter included" are done. 

![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/109147739/0c518eb3-80f8-48c2-b87a-6d85487a7304)
![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/109147739/89e28b67-e0f8-4434-8154-4505be11f101)

**Comment by olehivanovw** [comment]
@Viktoriia0106, In the story condition, only English letters were indicated. On your second screen you can see it: "Uppercase letters: A-Z, Lowercase letters: a-z" Therefore, only English letters are used at the moment.

**Comment by Viktoriia0106** [comment]
@olehivanovw you are absolutely right, but as a user who try to enter the password a have done the capital letter condition, but the system shows the error. The error message should be understandable (e.g. "пароль иає містити мінінму 9 символів, включаючи велику латинську літеру")

**Comment by olehivanovw** [comment]
Fix @Viktoriia0106 

I use your message, thanks. The error message understandable:

![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/121825752/47a74b74-8f43-4ea9-ad76-81873918b9e8)

Please make this issue is closed if the bug is fixed.
