### ISSUE TITLE
['Кабінет' Tab, Main page] The 404 page instead of the password's recovery page is shown after clicking the 'Забули пароль' button

### ISSUE THREAD

**Issue by Viktoriia0106** [kamilka13me/marketplace_teamchallenge#133]
**Environment:**
Windows 10 22H2 19045.4046, 64-bit
Google Chrome 121.0.6167.187, x64
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible:** always

**Build found:** 19.03.2024_14:20

**Steps to reproduce:**
1. The [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) site is opened
2. Click the 'Кабінет' icon in the header of the site
3. Click the 'Забули пароль' button
4. Pay attention to the result

**Actual result:**
The 404 page instead of the password's recovery page is shown after clicking the 'Забули пароль' button

**Expected result:**
The password's recovery page is shown after clicking the 'Забули пароль' button 

The bug is reproduced in 'Eng' localization as well.

[User story MT-15](https://marketplacetc.atlassian.net/browse/MT-15)
![password_recover_page](https://github.com/kamilka13me/marketplace_teamchallenge/assets/109147739/71fd5cb4-a0c2-4148-a21e-bb465d3aa5e7)

**Comment by olehivanovw** [comment]
@Viktoriia0106 
While the 404 page is a stub, because there is no password recovery page design, when the design appears, appropriate changes will be made immediately. (
