### ISSUE TITLE
[Personal Data form] The system is accepted the date of birth from the future instead of displaying an error message in the personal data form after entering the date from the future in the  ‘Дата народження’ field

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#141]
**Environment:**
Windows 10 Pro 19045.4046
Google Chrome 121.0.6167.187, x64
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible:**  always

**Build found:** 20.03.2024_15:00

**Preconditions:**

1. The user is registered
2. The Personal data form page  is opened

**Steps to reproduce:**

1. The [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) site is opened
2. Enter a valid Name (e.g. ‘Elina’)
3. Enter an invalid date of birthday ( e.g. ‘07.07.2077’)
4. Pay attention to the result

**Actual result:**

The system is accepted the date of birth from the future instead of displaying an error message in the personal data form after entering the date from the future in the  ‘Дата народження’ field. 'Зберегти' button is active

**Expected result:**

The system is not accepted the date of birth from the future, is displayed an error message in the personal data form after entering the date from the future in the ‘Дата народження’ field.  'Зберегти' button is not active

![2024-03-20 (3)](https://github.com/kamilka13me/marketplace_teamchallenge/assets/142516059/9f883b58-08a2-4c8c-8678-265e700251be)

[User Story MT-18/MT-20](https://marketplacetc.atlassian.net/jira/software/projects/MT/boards/1?selectedIssue=MT-20)

**Comment by olehivanovw** [comment]
Fix @ElinaApanasenko

Actual result:
The system is not accepedt a non-existent date of birth, is displayed an error message in the personal data form after entering a non-existent date in the ‘Дата народження’ field

![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/121825752/f463a97d-3f3c-43a0-91e5-c424a09154f3)


Please make this issue is closed if the bug is fixed.
