### ISSUE TITLE
[Personal Data form] The system is accepted a non-existent date of birth instead of displaying an error message on the personal data form after entering a non-existent date in the ‘Дата народження’ field 

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#142]
**Environment:**
Windows 10 Pro 19045.4046
Google Chrome 121.0.6167.187, x64
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible:**  always

**Build found**: 20.03.2024_15:00

**Preconditions:**

1. The user is registered
2. The Personal data form page  is opened

**Steps to reproduce:**

1. The [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) site is opened
2. Enter a valid Name (e.g. ‘Elina’)
3. Enter an invalid date of birthday ( e.g. ‘31.02.2024’)
4. Pay attention to the result

**Actual result:**
The system is accepted a non-existent date of birth instead of displaying an error message on the personal data form after entering a non-existent date in the ‘Дата народження’ field 

**Expected result:**
The system is not accepedt a non-existent date of birth, is displayed an error message in the personal data form after entering a non-existent date in the ‘Дата народження’ field

![2024-03-20 (2)](https://github.com/kamilka13me/marketplace_teamchallenge/assets/142516059/4b4bcf91-a4a0-48ef-b78a-2fe40c1ead72)

[User Story MT-18/MT-20](https://marketplacetc.atlassian.net/jira/software/projects/MT/boards/1?selectedIssue=MT-20)

**Comment by olehivanovw** [comment]
Fix @ElinaApanasenko

Actual result:
The system is not accepedt a non-existent date of birth, is displayed an error message in the personal data form after entering a non-existent date in the ‘Дата народження’ field

![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/121825752/689b41ae-2e6a-41e6-b64d-d0a1970ae892)


Please make this issue is closed if the bug is fixed.

**Comment by olehivanovw** [comment]
I apologize, the bug is still in the process of being fixed. The previous comment is not relevant.

**Comment by olehivanovw** [comment]
Fix @ElinaApanasenko

Added a check for the maximum number for each month, also added a check for the maximum number in February on a leap year.

![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/121825752/e5b7ad5b-b99c-466f-b8d4-cb8284e9c9ed)

![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/121825752/c549882d-9b1d-47f6-ba5e-39649476683a)

![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/121825752/b5c5dc55-a37a-4dbc-8e0b-2c4fa39a8d23)

**Comment by ElinaApanasenko** [comment]
@olehivanovw Good job)
