### ISSUE TITLE
[LogIn form/Maim page] The login form is disappeared on the main page after selecting the entered email with the cursor in the email field 

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#143]
**Environment:**
Windows 10 Pro 19045.4046
Google Chrome 121.0.6167.187, x64
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible**: not always

**Build found:** 20.03.2024_15:30

**Steps to reproduce:**

1. The [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) site is opened
2. Click the ‘Кабінет’ icon in the header of the site
3. Enter a valid E-mail (e.g. ‘23elina@gmail.com’)
4. Selecting (highlight)  the email with the cursor 
5. Pay attention to the result

**Actual result:**
The login window is disappeared on the main page after  selecting the entered email with the cursor in the email field 

**Expected result:**
The login window is remained open, the system is accepted the email, the error window is not displayed

[Video of bugs](https://drive.google.com/file/d/1fWFUMpVAMiwzZa4Xh_7L6HvOCezDRUnq/view?usp=sharing)

**Comment by olehivanovw** [comment]
Fix @ElinaApanasenko 

Actual result:
The login window is remained open, the system is accepted the email, the error window is not displayed

Please make this issue is closed if the bug is fixed.
