### ISSUE TITLE
[User account] surname from lowerCase

### ISSUE THREAD

**Issue by Sataxe7** [kamilka13me/marketplace_teamchallenge#179]
Steps to reproduce:

1.Open your account profile
2.Click on Surname and write there lowerCase.
Actual result:
True validation
![Screenshot_16](https://github.com/kamilka13me/marketplace_teamchallenge/assets/129331004/918a5a1a-9bfe-41ba-b743-fb562461132b)

![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/129331004/54b6c733-5c2a-4945-9711-b76bd10aec27)

Expected result:
Failed Validation because surname is lowerCase. Only first lower case letter acceptable

**Comment by olehivanovw** [comment]
@Sataxe7 Please make this issue is closed, because in Jira this bug closed.
