### ISSUE TITLE
[SideBar] Apple products inccorect displayed 

### ISSUE THREAD

**Issue by Sataxe7** [kamilka13me/marketplace_teamchallenge#191]
Steps to reproduce:
Open site
2.Click on Burger Menu
3.Select All categories
4.Select Apple products 
Actual result:
1. Apple products  have incorrect displayed.

https://github.com/kamilka13me/marketplace_teamchallenge/assets/129331004/d3a519c6-e23f-4f78-a029-e65dd4c4d3c5

Expected result:
1.Apple products are correct displayed

**Comment by Sataxe7** [comment]
There is still bug

**Comment by olehivanovw** [comment]
Fix @Sataxe7 

Please make this issue is closed if the bug is fixed.
