### ISSUE TITLE
[Header] missing language panel PC verison 

### ISSUE THREAD

**Issue by Sataxe7** [kamilka13me/marketplace_teamchallenge#193]
Steps to reproduce:

Open site
2.Pay attention to hover on language panel
3.Select All categories
Actual result:
1. On some resolution on PC language panel is missing.

https://github.com/kamilka13me/marketplace_teamchallenge/assets/129331004/2e348817-dd7c-44a2-8ad9-1714667b5330

Expected result:
On all resolution we could see language panel

**Comment by olehivanovw** [comment]
Fix @Sataxe7

Please make this issue is closed if the bug is fixed.
