### ISSUE TITLE
[Header] Incorrect display  icon of All Products and it's too big.

### ISSUE THREAD

**Issue by Sataxe7** [kamilka13me/marketplace_teamchallenge#194]
Steps to reproduce:

Open site
2.Click on Burger Menu
3.Pay attention to Header panel and to icon of all products.
Actual result:
1.Icon of all products not quite displayed and too big in some moments on Pc resolution

Expected result:
Icon of all products is quite displayed and have correct size in accordance with header.
https://github.com/kamilka13me/marketplace_teamchallenge/assets/129331004/3cbf02cf-390d-4361-b13a-3d4edff8d4d2

**Comment by olehivanovw** [comment]
Fix @Sataxe7 

Please make this issue is closed if the bug is fixed.
