### ISSUE TITLE
[Seller profile/Support page] The file is not attached to the seller's request on the support page 

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#211]
**Environment:**
iOS
Android

**Reproducible:** always

**Build found:** 26.04.2024_12:00

**Preconditions:**

1. The user is registered
2. The Support form page is opened

**Steps to reproduce:**

1. The [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) site is opened
2. Click the 'Select a file' button
3. Select a file with a valid format and size (max 5 files, max 10MB, png, jpg, pdf, doc, docx)
4. Click the 'Open' button
5. Pay attention to the result

**Actual result:**
The file is not attached to the seller's request on the support page 

**Expected result:**
The file is attached to the seller's request on the support page 

https://github.com/kamilka13me/marketplace_teamchallenge/assets/142516059/eb80e1c8-9e28-4452-8687-cefe2f4376b9

[Story - MT69](https://marketplacetc.atlassian.net/jira/software/projects/MT/boards/1?selectedIssue=MT-69)

**Comment by olehivanovw** [comment]
Fix @ElinaApanasenko 

Please make this issue is closed if the bug is fixed.
