### ISSUE TITLE
[Account Site] no validation message is displayed 

### ISSUE THREAD

**Issue by AlexTrofan** [kamilka13me/marketplace_teamchallenge#298]
Steps to reproduce:
1.Open site
2.Log in in your profile
3. Input in section your password password, and in the other one section of password confirmation inccorrect password 
Actual result:
1.No displayed message of invalid password cause they are not the same(only after clicking on button change data)
https://github.com/kamilka13me/marketplace_teamchallenge/assets/129331004/41fcdc37-6f41-407e-8d0e-90fd66ae3c1c
Expected result:
1.Displayed message of invalid password 
![Bug_No Validation Message](https://github.com/kamilka13me/marketplace_teamchallenge/assets/167144711/60cceaf7-8b0b-4115-972c-d1fa0c6ea549)

**Comment by Redddeve** [comment]
PR #441 
Fixed
