### ISSUE TITLE
[User Profile] After email verification, the message does not disappear

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#320]
![Баг — зроблено у Clipchamp](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/e997c680-8943-4d1f-8c35-007a735820f7)
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64
Microsoft Edge 125.0.2535.85  x64

Preconditions:

Registering a new account

Steps to reproduce:

1. Press the "Cabinet" button
2. In the lower part, click on the "Register" button
3. Fill in the fields "Name", "Email", "Your password"
4. Press the "I'm not a robot" button
5. Check the User Agreement checkbox
6. Click the "Register" button
7. In the personal account, in the mail verification message, send a letter 
8. Go to e-mail and verify it
9. Return to the personal account

Expected result:
After mail verification, the verification message disappears in the personal account

Actual result:
After mail verification, the verification message does not disappear in the personal account
![photo_2024-06-06_08-21-35](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/1a31a89f-c17d-4713-bd5f-a720a8006dcc)

**Comment by hunxjunedo** [comment]
requesting assignment.
