### ISSUE TITLE
[Seller] Reviews for the day are not displayed correctly

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#329]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64

Preconditions:
Log in to the site as a seller

Steps to reproduce:
1. In the left part of the seller's personal account, select the item "Reviews and ratings"
2. Select a category of reviews for the day

Expected result:
All reviews for today will be displayed

Actual result:
Reviews are displayed after selecting a date in the calendar
![Анімація](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/e013233c-8f07-44a4-819e-9472e8b8998b)

**Comment by olegpl1993** [comment]
fixed
