### ISSUE TITLE
[Ratings Page] The calendar is displayed on the right side of the page going beyond its borders on the Rating page in the mobile version

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#330]
**Environment:**

iPhone 14 ProMax
Samsung Galaxy S8+
iPhone6/7/8 +

**Reproducible:** always

**Build found:** 10.06.2024_15:00

**Preconditions:**

1. The user is registered
2. The Rating page is opened

**Steps to reproduce:**

1. The site [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) is opened
2. Сlick  the Сalendar icon
3. Pay attention to the location of the calendar

Actual result:
The calendar is displayed on the right side of the page going beyond its borders on the Rating page in the mobile version

Expected result:
The calendar is displayed in the center of the page, according to the mockup on the Rating page in the mobile version

[MT - 70](https://qamarketplace.atlassian.net/browse/QAM-8)

https://github.com/kamilka13me/marketplace_teamchallenge/assets/142516059/a05f2b5c-97b6-4db8-9614-3aa6e662cfc1

**Comment by olegpl1993** [comment]
fixed
