### ISSUE TITLE
[Reviews] The words are not spelled correctly

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#331]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64

Preconditions:
Log in to the site as a seller

Steps to reproduce:
1. In the left part of the seller's personal account, select the item "Manage products"
2. Open the product on which there are reviews
3. Scroll down to the required feedback
4. Click the "Dispute review" button
![Баг](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/e4478c5e-2ac5-470b-9edd-7921a775b4a6)

Expected result:
The text at the top of the window "Протягом 3х днів ми розглянемо ваш запит та видалимо відгук, якщо скарга є обгрунтованою", "Відгук залишений особою, пов'язаною з продавцем або конкурентом"
[MT-59](https://qamarketplace.atlassian.net/browse/QAM-1)

Actual result:
The text at the top of the window "Протягом 3х днів ми розглянемо ваш запит та видалимо відгук, якщо скарга є **_обргунтованою_**", "Відгук залишений особою, **_пов&apos;язаною_** з продавцем або конкурентом"
![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/01825eb6-6825-4eb3-a72b-beed60f0226e)

**Comment by olegpl1993** [comment]
fixed
