### ISSUE TITLE
[Response] The response to the review does not adapt to the text

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#336]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64
Microsoft Edge  125.0.2535.92 x64

Preconditions:
Go to the site [Peach](https://marketplace-teamchallenge.vercel.app/). 
Log in as a seller.

Steps to reproduce:
1. Go to the seller's page and select "Відгуки та рейтинги" on the left side of the menu
2. Select reviews for a certain period (for example, a week)
3. Select one of the reviews and start typing in the "Відповісти на відгук" field (Feedback text for example "Ця дитяча іграшка - просто чудова! Потяг збирається легко, має яскраві кольори та велику кількість вагончиків. Справжній засіб для розвитку уяви та моторики у вашої дитини. Рекомендую! Вона точно стане улюбленою грашкою вашого малюка.")

Expected result:
The width of the field for entering a response to feedback adapts to the amount of text
[MT-59](https://qamarketplace.atlassian.net/browse/QAM-1)

Actual result:
The text is hidden behind the send arrow. The field does not adapt to the amount of text
![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/f61f7f9d-7015-4495-89e8-525f835f15ba)
![Баг відповіді на відгук](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/952a7ab6-2706-437a-984e-523cc026ecc1)

**Comment by olegpl1993** [comment]
fixed
