### ISSUE TITLE
[Response]  A posted response to a review goes beyond the review block

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#337]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64
Microsoft Edge 125.0.2535.92 x64

Preconditions:
Go to the site [Peach](https://marketplace-teamchallenge.vercel.app/).
Log in as a seller.

Steps to reproduce:

Go to the seller's page and select "Відгуки та рейтинги" on the left side of the menu

Select one of the reviews and start typing in the "Відповісти на відгук" field (Feedback text for example "Ця дитяча іграшка - просто чудова! Потяг збирається легко, має яскраві кольори та велику кількість вагончиків. Справжній засіб для розвитку уяви та моторики у вашої дитини. Рекомендую! Вона точно стане улюбленою грашкою вашого малюка.")
Click on the "Відправити" button
Under the feedback, click "Дивитися відповідь"

Expected result:
After expanding the answers to the feedback, the site adapts to the size of the text
[MT-59](https://qamarketplace.atlassian.net/browse/QAM-1)

Actual result:
After the responses to the feedback are expanded, the text goes outside the site
![Баг flfgnbdyjcns d rf,sytns ghjlfdwz](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/0d79b638-0116-4cac-8f55-50d059216f2a)

**Comment by olegpl1993** [comment]
Bug is don't repeated.
Site correctly adapts to the size of the text.

![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/79967092/d592446f-f491-40fa-96c3-165486268a57)
