### ISSUE TITLE
[MT-88] [Publications] The ad duplication button does not work correctly

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#360]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64 (iPhone 12 Pro 390x844)

Preconditions:
Go to [Peach](https://marketplace-teamchallenge.vercel.app/). Log in as a seller.

Steps to reproduce:

Open all ads in the seller's account
Click on the three dots and select the duplicate ad item

Expected result:
The selected ad will be duplicated
[MT-88](https://qamarketplace.atlassian.net/browse/QAM-9)

Actual result:
The selected ad is deleted
![Баг дублювання оголошення](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/cec156f9-0ed8-4617-91d4-1e25eb7d6181)

**Comment by olegpl1993** [comment]
Fixed
delete this button from maket
