### ISSUE TITLE
[Search bar] After entering title in search bar error 404(Щось пішло не так  )

### ISSUE THREAD

**Issue by AlexTrofan** [kamilka13me/marketplace_teamchallenge#361]
**Steps to reproduce:**
Open site
2.Click on Search bar
3.Type some product in search bar like Енот
4.enter ok
**Actual result:**
1. Сrashing site after clicking  on button ok
**Expected result:**
1.Apperaring of products on the site. 

https://github.com/kamilka13me/marketplace_teamchallenge/assets/167144711/b4c30bfa-abcd-47fb-9afd-450c67a12071

**Comment by olegpl1993** [comment]
Fixed Products Page
