### ISSUE TITLE
[Categories with products] After clicking on categories with product crashing site 

### ISSUE THREAD

**Issue by AlexTrofan** [kamilka13me/marketplace_teamchallenge#362]
### Steps to reproduce:
1.Open site
2.Choose  any category from button All products with accessible product in that category 
3.Click on it 
### Actual result:
Crashing site.
Expected result:
Displayed products  in that category, and you click on that.

https://github.com/kamilka13me/marketplace_teamchallenge/assets/167144711/c07f337d-238d-4950-bf34-443c12194b6e

**Comment by olegpl1993** [comment]
Fixed Products Page
