### ISSUE TITLE
[MT-50] [Update products] After changing the product description, the change is not displayed

### ISSUE THREAD

**Issue by ruslanamudrats** [kamilka13me/marketplace_teamchallenge#365]
Environment:
Windows 10Pro 19045.4509

Preconditions:
Go to [Peach](https://marketplace-teamchallenge.vercel.app/). Log in as a seller.

Steps to reproduce:

1.Add the product to the list
2.Click on the bottom Edit
3.Make changes
4.Click Save

Expected result:
Сhanges are reflected in the product

Actual result:
Сhanges are

https://github.com/kamilka13me/marketplace_teamchallenge/assets/119169128/dfabcf2c-8d4b-4a95-8193-66f76cf09a93

 not displayed

**Comment by olegpl1993** [comment]
fixed
