### ISSUE TITLE
[MT-72] [Publications] Incorrect discount setting

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#366]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64

Preconditions:
Go to [Peach](https://marketplace-teamchallenge.vercel.app/). 
Log in as a seller. 
Login: somene6489@dalebig.com
Password: 12345678910A

Steps to reproduce:
Go to the product editing page
Scroll to the product price setting block
Use the radio button to select "Set discount"
![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/cf8ccdb9-de2a-4943-992a-da34ec76b24d)
Enter a minus figure in the discount percentage field

Expected result:
It is not possible to enter a negative discount percentage
[MT-72](https://qamarketplace.atlassian.net/browse/QAM-22)

Actual result:
The minus indicator of the discount is taken into account
![Баг відсотку знижки](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/09d21221-c42f-4cd3-865e-3ab75e102914)

**Comment by olegpl1993** [comment]
fixed
If the field contains an incorrect value, you will not be able to submit the form.
![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/79967092/c7aa9971-6d7c-4947-8f8b-9e0608609cb6)
![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/79967092/092e9640-ef6f-4e40-9614-8cb879acf16b)
