### ISSUE TITLE
[MT-72] [Publications] Invalid date range

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#367]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64

Preconditions:
Go to [Peach](https://marketplace-teamchallenge.vercel.app/).
Log in as a seller.
Login: somene6489@dalebig.com
Password: 12345678910A

Steps to reproduce:
Go to the product editing page
Scroll to the product price setting block
Use the radio button to select "Set discount"
Enter the start and end date of the discount

Expected result:
An indicator earlier than the start date cannot be entered in the end date
[MT-72](https://qamarketplace.atlassian.net/browse/QAM-22)

Actual result:
An indicator earlier than the start date cannot be entered in the end date
![Баг періоду знижок](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/58db3cc6-c305-45ce-a192-ace6834767b7)

**Comment by olehivanovw** [comment]
Fixed @olegpl1993
