### ISSUE TITLE
[MT-72] [Publications] There is no calendar for selecting dates

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#368]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64

Preconditions:
Go to [Peach](https://marketplace-teamchallenge.vercel.app/).
Log in as a seller.
Login: [somene6489@dalebig.com](mailto:somene6489@dalebig.com)
Password: 12345678910A

Steps to reproduce:
Go to the product editing page
Scroll to the product price setting block
Use the radio button to select "Set discount"
Enter the start and end date of the discount

Expected result:
When the discount date field is activated, a calendar appears for selecting the start/end date of the discount
[MT-72](https://qamarketplace.atlassian.net/browse/QAM-22)

Actual result:
When activating the field, the discount dates must be entered manually.
![Баг відсутності календаря](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/e171bc64-283e-458a-8923-5be4658da4b0)

**Comment by olegpl1993** [comment]
fixed
Create calendar foe select date
