### ISSUE TITLE
[MT-72] [Publications] Incorrect dates

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#369]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64

Preconditions:
Go to [Peach](https://marketplace-teamchallenge.vercel.app/).
Log in as a seller.
Login: [somene6489@dalebig.com](mailto:somene6489@dalebig.com)
Password: 12345678910A

Steps to reproduce:
Go to the edit product page
Go to the product price setting block
Use the switch to select "Set Discount"
Enter the start date (for example, 31.02.2024) and the discount end date (31.06.2024)

Expected result:
Such dates do not exist and there will be an error
[MT-72](https://qamarketplace.atlassian.net/browse/QAM-22)

Actual result:
Dates are accepted without errors
![Баг валідності дат](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/3f6ceab9-20d5-4e06-9502-db2b4ab6acc0)

**Comment by olegpl1993** [comment]
fixed
create calendar for select date
