### ISSUE TITLE
[MT-72] [Publications] Products without photos

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#371]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64

Preconditions:
Go to [Peach](https://marketplace-teamchallenge.vercel.app/).
Log in as a seller.
Login: [somene6489@dalebig.com](mailto:somene6489@dalebig.com)
Password: 12345678910A

Steps to reproduce:
Go to edit post
Delete the previously added photo
Save changes

Expected result:
Error. You need to upload at least 1 photo
[MT-72](https://qamarketplace.atlassian.net/browse/QAM-22)

Actual result:
Changes are saved without a photo
![Баг пропуску без фото](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/cc55d95d-201d-4947-b512-bc0a6c842eb1)

**Comment by olegpl1993** [comment]
fixed
