### ISSUE TITLE
[Seller panel] The seller can upload a photo over 10 MB on the product creation page

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#374]
**Environment:**

Windows 10 Pro 19045.4046
Google Chrome 121.0.6167.187, x64
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible:** always

**Build found:** 22.06.2024_18:00

**Preconditions:**

1. The user is registered
2. The Product page is opened
3. All required fields are filled in
4. No photos have been added

**Steps to reproduce:**

1. The site [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) is opened
2. Сlick the  "Завантажити ще 8 фоторгафії" button
3. Click  the empty photo field
4. Choose a photo from a computer larger than 10 MB
5. Click the "Зберегти" button
6. Pay attention to the photo of the product

**Actual result:**
The seller can upload a photo over 10 MB on the product creation page

**Expected result:**
The seller can not  upload a photo over 10 MB on the product creation page

https://github.com/kamilka13me/marketplace_teamchallenge/assets/142516059/cad5cf8f-52f2-47c6-ae02-29c62c10368b

[MT - 72 / 81](https://qamarketplace.atlassian.net/jira/software/projects/QAM/boards/1?selectedIssue=QAM-23)

**Comment by olegpl1993** [comment]
fixed
