### ISSUE TITLE
[Seller panel ]The product is not saved on the product creation page after clicking the "Зберегти" button

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#375]
**Environment:**

Windows 10 Pro 19045.4046
Google Chrome 121.0.6167.187, x64
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible:** always

**Build found:** 22.06.2024_18:00

**Preconditions:**

1. The user is registered
2. The Product page is opened
3. All required fields are filled in
 
**Steps to reproduce:**

1. The site [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) is opened
2. Click the "Зберегти" button
3. Pay attention to the page

**Actual result:**
The product is not saved on the product creation page after clicking the "Зберегти" button, the product creation page is open 

**Expected result:**
The created product is added to the seller's page

https://github.com/kamilka13me/marketplace_teamchallenge/assets/142516059/726a0be1-a11b-4dc8-aede-70a1dd28761d

[МТ - 81 / 72](https://qamarketplace.atlassian.net/jira/software/projects/QAM/boards/1?selectedIssue=QAM-23)

**Comment by olehivanovw** [comment]
[Bugfix/MT-198/Seller-product-validation](https://github.com/kamilka13me/marketplace_teamchallenge/pull/443)

**Comment by olehivanovw** [comment]
Fixed.
