### ISSUE TITLE
[Seller panel]The created product is not available on the product management page after clicking the "Зберегти" button

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#376]
**Environment:**

Windows 10 Pro 19045.4046
Google Chrome 121.0.6167.187, x64
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible:** always

**Build found:** 22.06.2024_18:00

**Preconditions:**

1. The user is registered
2. The Product page is opened
3. All required fields are filled in

**Steps to reproduce:**

1. The site [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) is opened
2. Click the "Зберегти" button
3. Pay attention to the product management page

**Actual result:**
The created product is not available on the product management page after clicking the "Зберегти" button

**Expected result:**
The created product is  available on the product management page after clicking the "Зберегти" button

https://github.com/kamilka13me/marketplace_teamchallenge/assets/142516059/b75ab8a2-d751-47dd-8f12-7fef90bda2fa

[МТ - 81 / 72](https://qamarketplace.atlassian.net/jira/software/projects/QAM/boards/1?selectedIssue=QAM-23)

**Comment by olehivanovw** [comment]
[Bugfix/MT-198/Seller-product-validation](https://github.com/kamilka13me/marketplace_teamchallenge/pull/443)

**Comment by olehivanovw** [comment]
Fixed.
