### ISSUE TITLE
[Seller panel] The calendar is not opened on the product creation page after clicking on the "Start date" and "End date" fields 

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#377]
**Environment:**

Windows 10 Pro 19045.4046
Google Chrome 121.0.6167.187, x64
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible:** always

**Build found:** 22.06.2024_18:00

**Preconditions:**

1. The user is registered
2. The Product page is opened
3. All required fields are filled in

**Steps to reproduce:**

1. The site [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) is opened
2. Click the "Встановити знижку "button
3. Сlicking  the "Start date"  fields 
4. Сlicking  the  "End date" fields 
5. Pay attention to the calendar fields

**Actual result:**
The calendar is not opened on the product creation page after clicking on the "Start date" and "End date" fields 

**Expected result:**
The calendar is  opened on the product creation page after clicking on the "Start date" and "End date" fields 

https://github.com/kamilka13me/marketplace_teamchallenge/assets/142516059/4ec56925-35fa-4463-98af-1eda4e6de69e

[МТ - 81 / 72](https://qamarketplace.atlassian.net/jira/software/projects/QAM/boards/1?selectedIssue=QAM-23)

**Comment by olehivanovw** [comment]
Fixed @olegpl1993
