### ISSUE TITLE
[Admin panel] Аn error is displayed on the announcements page after clicking the "Опублікувати" button

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#378]
**Environment:**

Windows 10 Pro 19045.4046
Google Chrome 121.0.6167.187, x64
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible:** always

**Build found:** 22.06.2024_18:00

**Preconditions:**

1. The Announcements page is opened
2. Added  one listing by seller's page

**Steps to reproduce:**

1. The site [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) is opened
2. Сlick on the Actions button next to the added product
3. Click the "Опублікувати" button
4. Pay attention to the page

**Actual result:**
Аn error is displayed on the announcements page after clicking the "Опублікувати" button

**Expected result:****
The "Announcement successfully published" message is displayed on the page

https://github.com/kamilka13me/marketplace_teamchallenge/assets/142516059/e9fc0f22-4de8-437b-8d3f-fd639050b519

**Comment by olegpl1993** [comment]
fixed
