### ISSUE TITLE
[Admin panel] The action window is not closed and is displayed incorrectly on the announcements page

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#379]
**Environment:**

Windows 10 Pro 19045.4046
Google Chrome 121.0.6167.187, x64
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible:** always

**Build found:** 22.06.2024_18:00

**Preconditions:**

1. The Announcements page is opened
2. Added min one listing by seller's page

**Steps to reproduce:**

1. The site [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) is opened
2. Сlick  the Actions button 
3. Сlick  an empty field on the page
4. Pay attention to the Action buttons

**Actual result:**
The action window is not closed and is displayed incorrectly on the announcements page

**Expected result:****
The action window is closed and is displayed correctly on the announcements page

https://github.com/kamilka13me/marketplace_teamchallenge/assets/142516059/84e32ee1-787f-4d9f-9ece-ce8ff0d60cc0

**Comment by Redddeve** [comment]
Fixed
