### ISSUE TITLE
[Seller page] The number of ads on the Subscribes page is not matched the mockup

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#380]
**Environment:**

Windows 10 Pro 19045.4046
Google Chrome 121.0.6167.187, x64
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible:** always

**Build found**: 22.06.2024_18:00

**Preconditions:**

1. The Subscribes page is opened

**Steps to reproduce:**

1. The site [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) is opened
2. Check the number of ads on the tariff plan

**Actual result:**
The number of ads on the Subscribes page is not matched the mockup

**Expected result:****
The number of ads on the Subscribes page is not matched the mockup

![Screenshot_9](https://github.com/kamilka13me/marketplace_teamchallenge/assets/142516059/a3deb757-ace4-47cd-a751-6f5e51e892c4)

**Comment by olegpl1993** [comment]
fixed
