### ISSUE TITLE
[Seller registration] The data is not saved on the Seller registration page after clicking the "Зберегти" button 

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#381]
**Environment:**

Windows 10 Pro 19045.4046
Google Chrome 121.0.6167.187, x64
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible:** not always

**Build found:** 22.06.2024_18:00

**Preconditions:**

1. The Seller registration  page is opened
2. All required fields are filled with correct data

**Steps to reproduce:**

1. The site [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) is opened
2. Сlick the "Зберегти" button
3. Pay attention to the page

**Actual result:**
The data is not saved on the Seller registration page after clicking the "Зберегти" button 

**Expected result:**
The data is  saved on the Seller registration page after clicking the "Зберегти" button and Seller is registered

https://github.com/kamilka13me/marketplace_teamchallenge/assets/142516059/6315fe00-be6e-4f11-9b23-f4594b084a8b

[MT - 93 / 85](https://qamarketplace.atlassian.net/jira/software/projects/QAM/boards/1?selectedIssue=QAM-24)

**Comment by olehivanovw** [comment]
[Bugfix/MT-197/Seller-validation](https://github.com/kamilka13me/marketplace_teamchallenge/pull/435)

**Comment by olehivanovw** [comment]
Fixed.
