### ISSUE TITLE
[Product page] The price is not matched the discount on the product page

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#384]
**Environment:**

Windows 10 Pro 19045.4046
Google Chrome 121.0.6167.187, x64
Microsoft Edge 122.0.2365.52, 64-bit
Firefox Browser 123.0, 64-bit

**Reproducible:** always

**Build found:** 23.06.2024_21:00

**Preconditions:**

1. The Product page is opened

**Steps to reproduce:**

1. The site [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) is opened
2. Pay attention to the price and sale of the product

**Actual result:**
The price is not matched the discount on the product page

**Expected result:**
The price is matched the discount on the product page

![Screenshot_11](https://github.com/kamilka13me/marketplace_teamchallenge/assets/142516059/8a772abf-837a-4e0a-a0d2-623a90ab04a8)

[MT - 43](https://qamarketplace.atlassian.net/jira/software/projects/QAM/boards/1?selectedIssue=QAM-43)

**Comment by olegpl1993** [comment]
Fixed.
Add validation for input create discount.  min - 1% max - 99%
