### ISSUE TITLE
[MT-118] Incorrect display of the search result by seller ID

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#393]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64

Preconditions:
Go to [Peach](https://marketplace-teamchallenge.vercel.app/).
Log in as a admin.

Steps to reproduce:
Go to the announcements section
Select the Seller ID on this page and paste it into the appropriate search field
Go to page 2, select the seller's ID there and insert it into the corresponding search field (repeat on all pages)

Expected result:
Search results will be displayed on all pages
[MT-118](https://qamarketplace.atlassian.net/browse/QAM-53)

Actual result:
The results are displayed only when the seller's ID is entered on the first page (the seller's ID from the 4th page will be found when searching on the first page)
![Баг адмін панелі оголошення](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/9f565df5-c3be-491c-b806-e2661cc48b1e)

**Comment by Redddeve** [comment]
Fixed
