### ISSUE TITLE
[MT-118]  Access to product rejection after publication

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#394]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64

Preconditions:
Go to [Peach](https://marketplace-teamchallenge.vercel.app/).
Log in as a admin.

Steps to reproduce:
Go to the announcements section
Choose to sort products by Published
Click on the 3 dots next to the product in the Actions column
Press the reject button

Expected result:
The post rejection button should not work after the product is published
[MT-118](https://qamarketplace.atlassian.net/browse/QAM-53)

Actual result:
The product can be rejected after the product has been published
![Баг дій з опублікованою публікацією](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/fdfede06-730c-4d0b-bb8b-911c4238f3b6)

**Comment by olegpl1993** [comment]
fixed
