### ISSUE TITLE
[MT-118] When switching from the second page of results, the results on other pages are not displayed

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#395]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64

Preconditions:
Go to [Peach](https://marketplace-teamchallenge.vercel.app/).
Log in as a admin.

Steps to reproduce:
Go to the announcements section
Select the Seller ID on this page and paste it into the appropriate search field
Go to page 2, select the seller's ID there and insert it into the corresponding search field (repeat on all pages)

Expected result:
The result is applied from all pages
[MT-118](https://qamarketplace.atlassian.net/browse/QAM-53)

Actual result:
When moving from page 2 of the results found on other pages in the Published/Rejected/Blocked tabs, there will be no results

![Баг відображення за ІД](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/a376f5e3-b142-4217-a0aa-fd90ffdfe593)

**Comment by Redddeve** [comment]
Fixed
