### ISSUE TITLE
[MT-118] Incorrect display when sorting by dates

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#396]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64

Preconditions:
Go to [Peach](https://marketplace-teamchallenge.vercel.app/).
Log in as a admin.

Steps to reproduce:
Go to the announcements section
Choose a period, for example, from June 1 to today
Check the result

Expected result:

All results from June 1 to today will be selected
[MT-118](https://qamarketplace.atlassian.net/browse/QAM-53)

Actual result:
Sorting is not applied
![Баг сортування за датою](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/3df490a3-3afa-43c7-8a18-bcbef325d153)

**Comment by olegpl1993** [comment]
fixed
