### ISSUE TITLE
[Seller registration/Mobile version ] The data is not saved on the Seller registration page after clicking the "Зберегти" button 

### ISSUE THREAD

**Issue by ElinaApanasenko** [kamilka13me/marketplace_teamchallenge#401]
**Environment:**

iPhone 14 Pro Max

**Reproducible:** always

Build found: 28.06.2024_21:00

**Preconditions:**

1. The Seller registration page is opened
2. All required fields are filled with correct data

**Steps to reproduce:**

1. The site [Peach](https://marketplace-teamchallenge-git-dev-kamilka13mes-projects.vercel.app/) is opened
2. Сlick the "Зберегти" button
3. Pay attention to the page

**Actual result:**
The data is not saved on the Seller registration page after clicking the "Зберегти" button

**Expected result:**
The data is saved on the Seller registration page after clicking the "Зберегти" button and Seller is registered

https://github.com/kamilka13me/marketplace_teamchallenge/assets/142516059/2218b117-e290-40d4-a51e-8ef92f852cae

[MT - 119](https://qamarketplace.atlassian.net/jira/software/projects/QAM/boards/1?selectedIssue=QAM-52)

**Comment by olehivanovw** [comment]
#Bugfix/MT-197/Seller-validation

**Comment by olehivanovw** [comment]
Fixed.
