### ISSUE TITLE
[MT-153] Issue with displaying full seller ID and searching by ID

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#412]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64

Preconditions:
Go to [Peach](https://marketplace-teamchallenge.vercel.app/).
Log in as a admin.

Steps to reproduce:
Go to the Finances section
Click on the seller's ID
Copy the seller's ID and perform a search by the ID in the corresponding search field
Copy the company name and search by name
Copy part of a company name and find all matches by partial search

Expected result:
The seller's ID is displayed in full and when clicked, it is copied for further search
[MT-153](https://qamarketplace.atlassian.net/browse/QAM-70)

Actual result:
When clicking on the ID and the name, the data is not copied. The seller's ID is not fully displayed, which is why the search by ID does not work
![Баг роботи з пошуком ІД](https://github.com/kamilka13me/marketplace_teamchallenge/assets/157404539/c84a6d70-e7b1-48d5-a3a8-f069802878de)

**Comment by Nikolay0803** [comment]
bug done

**Comment by Nikolay0803** [comment]
bug done
