### ISSUE TITLE
no warning to the user that the old password is the same as the new

### ISSUE THREAD

**Issue by YULIIA260600** [kamilka13me/marketplace_teamchallenge#417]
Environment: 
Windows 10 Pro 19045.4598
Google Chrome  126.0.6478.127 x64 
Preconditions:
Go to the "кабінет" section 
In the " новий пароль " field enter old password data
Expected result:
see the warning message "це існуючий пароль»
Actual result:
old password data is accepted as new

**Comment by Nikolay0803** [comment]
Bug fixed
