### ISSUE TITLE
[MT-135] Actions of the drop-down menu of items on the announcements page not working.

### ISSUE THREAD

**Issue by yana-sukha1998** [kamilka13me/marketplace_teamchallenge#421]
Environment:
Windows 1O Home
Google Chrome 126.0.6478.127

Preconditions:
Go to [Peach](https://marketplace-teamchallenge.vercel.app/).
Log in as an admin.

Steps to reproduce:
1. Go to the announcement pages.   
2. Click on the action on the drop-down menu.
3. One by one, click on edit publish, reject, block

Expected result:
Actions of the drop-down menu of items on the announcements page not working.

Actual result:
Actions of the drop-down menu of items on the announcements page working.

**Comment by yana-sukha1998** [comment]
https://github.com/kamilka13me/marketplace_teamchallenge/assets/129494032/10ae81b9-438a-4428-b1a9-d17e310b2568

**Comment by Redddeve** [comment]
Fixed
