### ISSUE TITLE
Field requirements for registration

### ISSUE THREAD

**Issue by YULIIA260600** [kamilka13me/marketplace_teamchallenge#429]
Environment: 
Windows 10 Pro 19045.4598
Google Chrome  126.0.6478.127 x64 
Preconditions:
Go to Peach.
New seller registration
Steps to reproduce
1 Go to Peach.
2. button «стати продавцем»
3. The Seller registration page is opened
4. field "індекс" is filled with incorrect data
Expected result:
The postcode is not accepted, we see the inscription "індекс має бути з 5 цифр»
Actual result:
the postcode is accepted
![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/174318426/3d8565c0-b69a-4d09-a5ee-ef9691c4f4dc)

**Comment by olehivanovw** [comment]
[Bugfix/MT-197/Seller-validation](https://github.com/kamilka13me/marketplace_teamchallenge/pull/435)

**Comment by olehivanovw** [comment]
Fixed.
