### ISSUE TITLE
The field requirements for registration are incorrect

### ISSUE THREAD

**Issue by YULIIA260600** [kamilka13me/marketplace_teamchallenge#430]
Environment:
Windows 10 Pro 19045.4598
Google Chrome 126.0.6478.127 x64
Preconditions:
Go to Peach.
New seller registration
Steps to reproduce
1 Go to Peach.
2. button «стати продавцем»
3. The Seller registration page is opened
4. field "ІПН" is filled with incorrect data
Expected result:
The "ІПН" is not accepted, we see the inscription "ІПН має бути з 12 цифр»
Actual result:
the "ІПН" is accepted
![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/174318426/3deebd85-e61f-4300-9bd5-3e3e1783ad50)

**Comment by olehivanovw** [comment]
[Bugfix/MT-197/Seller-validation](https://github.com/kamilka13me/marketplace_teamchallenge/pull/435)

**Comment by olehivanovw** [comment]
Fixed.
