### ISSUE TITLE
incorrect requirements for registration fields

### ISSUE THREAD

**Issue by YULIIA260600** [kamilka13me/marketplace_teamchallenge#431]
Environment:
Windows 10 Pro 19045.4598
Google Chrome 126.0.6478.127 x64
Preconditions:
Go to Peach.
New seller registration
Steps to reproduce
1 Go to Peach.
2. button «стати продавцем»
3. The Seller registration page is opened
4. field "Місто, область" is filled with incorrect data "44"
Expected result:
The "Місто, область" is not accepted, we see the inscription "Місто, область має бути лише з літер"
Actual result:
the "Місто, область" is accepted
![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/174318426/9f0d2ab8-1e95-4245-ad08-4ec82d8e6817)

**Comment by olehivanovw** [comment]
[Bugfix/MT-197/Seller-validation](https://github.com/kamilka13me/marketplace_teamchallenge/pull/435)

**Comment by olehivanovw** [comment]
Fixed.
