### ISSUE TITLE
incorrect requirements for registration fields

### ISSUE THREAD

**Issue by YULIIA260600** [kamilka13me/marketplace_teamchallenge#432]
Environment:
Windows 10 Pro 19045.4598
Google Chrome 126.0.6478.127 x64
Preconditions:
Go to Peach.
New seller registration
Steps to reproduce
1 Go to Peach.
2. button «стати продавцем»
3. The Seller registration page is opened
Expected result:
Only one field is required to fill in: “IПН для ФОП” or "ЄДРПОУ для юр. осіб"
Actual result:
requires filling out 2 fields for different forms of ownership at the same time
![image](https://github.com/kamilka13me/marketplace_teamchallenge/assets/174318426/f97481ae-4637-485c-8e21-d48568ca0a39)

**Comment by olehivanovw** [comment]
[Bugfix/MT-197/Seller-validation](https://github.com/kamilka13me/marketplace_teamchallenge/pull/435)

**Comment by olehivanovw** [comment]
Fixed.
