### ISSUE TITLE
[MT-154] Page margins extend beyond the screen

### ISSUE THREAD

**Issue by ArishaQWERTY** [kamilka13me/marketplace_teamchallenge#445]
Environment:
Windows 11 Pro 22631.3593
Google Chrome 125.0.6422.142 x64

iPhone 12mini iOS 17.5.1

Preconditions:
Go to [Peach](https://marketplace-teamchallenge.vercel.app/).
Log in as an administrator from the mobile version.

Steps to reproduce:
Go to the Finances section
View the tariff plan of the company

Expected result:
All fields will be clearly displayed and adapted to the size of the user's screen
[MT-154](https://qamarketplace.atlassian.net/browse/QAM-82)

Actual result:
Part of the Tariff plan field and Tariff plan adjustment go beyond the screen

https://github.com/user-attachments/assets/b4d43831-4640-4f62-92f1-09e4b400b7ad

![Баг адаптації мобільної версії](https://github.com/user-attachments/assets/840245bb-1389-4bf6-b444-d80206f0e9b5)

**Comment by olegpl1993** [comment]
fixed
